export type AppRouteName =
  | 'Auth'
  | 'Home'
  | 'Capture'
  | 'More'
  | 'Timeline'
  | 'MemoryEventDetails'
  | 'MemoryThreads'
  | 'NoteDetails'
  | 'Insights'
  | 'Actions'
  | 'Reminders'
  | 'Search'
  | 'DeviceManagement'
  | 'Settings';
