import { Injectable } from '@nestjs/common';
import { Processor, WorkerHost } from '@nestjs/bullmq';
import { QUEUE_NAMES } from '@voxa/shared';
import { Job } from 'bullmq';
import { PrismaService } from '../prisma/prisma.service';
import { QueueService } from '../queue/queue.service';
import { AiPipelineJobData } from './transcription.worker';

@Injectable()
@Processor(QUEUE_NAMES.SUMMARY)
export class SummaryWorker extends WorkerHost {
  constructor(
    private readonly prisma: PrismaService,
    private readonly queueService: QueueService,
  ) {
    super();
  }

  async process(job: Job<AiPipelineJobData>) {
    const { aiJobId, recordingId, memoryEventId, userId } = job.data;
    await this.markProcessing(aiJobId);

    const note = await this.prisma.note.upsert({
      where: { memoryEventId },
      update: {
        title: 'Mock memory summary',
        summary: 'TODO: Replace this with SummaryProvider output.',
        body: 'This placeholder note is generated by the MVP summary worker.',
      },
      create: {
        userId,
        memoryEventId,
        title: 'Mock memory summary',
        summary: 'TODO: Replace this with SummaryProvider output.',
        body: 'This placeholder note is generated by the MVP summary worker.',
      },
    });

    await this.prisma.memoryEvent.update({
      where: { id: memoryEventId },
      data: {
        title: note.title,
        summary: note.summary,
      },
    });

    const completedJob = await this.markCompleted(aiJobId);
    const actionJob = await this.createAiJob(userId, recordingId, memoryEventId, 'action_extraction', {
      noteId: note.id,
    });
    const queuedJob = await this.queueService.enqueueActionExtraction({
      aiJobId: actionJob.id,
      recordingId,
      memoryEventId,
      userId,
      noteId: note.id,
    });

    return { noteId: note.id, aiJobId: completedJob.id, queuedJob };
  }

  private markProcessing(aiJobId: string) {
    return this.prisma.aiJob.update({
      where: { id: aiJobId },
      data: { status: 'processing', startedAt: new Date(), attempts: { increment: 1 } },
    });
  }

  private markCompleted(aiJobId: string) {
    return this.prisma.aiJob.update({
      where: { id: aiJobId },
      data: { status: 'completed', completedAt: new Date() },
    });
  }

  private createAiJob(
    userId: string,
    recordingId: string,
    memoryEventId: string,
    type: 'action_extraction',
    payload: Record<string, string>,
  ) {
    return this.prisma.aiJob.create({
      data: { userId, recordingId, memoryEventId, type, status: 'pending', payload },
    });
  }
}
